database:
  host: localhost
  port: 3306
  database: lemonpvp
  username: root
  password: password

maintenance:
  # Discord invite link shown in the maintenance kick message
  discord-link: "https://discord.gg/eZWP9EGW7"
