database:
  host: 172.18.0.1
  port: 3306
  database: s1_LemonPvP_Network
  username: u1_zMGE6ZE7k8
  password: "I.W3m6k5Yb@sZxtwFbtBey9C"
  pool-size: 10

server-type: LOBBY  # LOBBY or DUELS

prices:
  trim-pattern: 250
  trim-material: 50

velocity:
  channel: lemoncosmetics:main

discord:
  invite: "https://discord.gg/lemonpvp"
