database:
  host: localhost
  port: 3306
  database: s1_LemonPvP_Network
  username: u1_zMGE6ZE7k8
  password: "I.W3m6k5Yb@sZxtwFbtBey9C"

server-name: lobby
restart:
  time: "02:30"
  timezone: "Europe/Berlin"
