name: LemonLobby
version: 1.0.0
main: com.lemonpvp.lemonlobby.LemonLobby
api-version: '1.21'
softdepend: [LuckPerms, LemonCore]
commands:
permissions:
  lemonlobby.admin:
    description: Admin access
    default: op
