name: LemonBuild
version: "1.0.0"
main: com.lemonpvp.lemonbuild.LemonBuild
api-version: "1.21"
description: LemonPvP World-Builder (Spawn-Generator)
authors: [LemonPvP]
softdepend: [FastAsyncWorldEdit, WorldEdit]

permissions:
  lemonbuild.admin:
    description: Alle Build-Befehle nutzen
    default: op

commands:
  aowbuildlobby:
    description: Baut die Lobby-Spawn-Insel an Weltmitte (0, 64, 0)
    usage: /aowbuildlobby [confirm]
    permission: lemonbuild.admin
    aliases: [buildlobby]
