#!/usr/bin/env python3
"""
Texturen und 3D-Modelle für die mitgelieferten Inhalte
======================================================

Erzeugt alles prozedural - kein Grafikprogramm nötig:

  src/main/resources/assets/textures/block/<id>.png   50 Möbel
  src/main/resources/assets/textures/item/<id>.png    Fahrzeuge, Waffen, Schirm
  src/main/resources/assets/models/block/<id>.json    echte Möbelformen
  src/main/resources/assets/models/item/<id>.json     Autos, Flieger

Das Plugin legt diese Dateien beim ersten Start in
plugins/SMPContent/textures/ und models/ ab. Wer etwas schöner haben
will, überschreibt einfach die Datei - beim nächsten /smpcontent pack
ist die eigene drin.

    python3 texturen.py
"""

import json
import math
import random
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).parent
TEX = ROOT / "src/main/resources/assets/textures"
MOD = ROOT / "src/main/resources/assets/models"

S = 16  # Kantenlänge einer Textur


# ---------------------------------------------------------------- Werkzeug

def img():
    return Image.new("RGBA", (S, S), (0, 0, 0, 0))


def hexc(value, alpha=255):
    value = value.lstrip("#")
    return (int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16), alpha)


def mix(a, b, t):
    return tuple(round(a[i] + (b[i] - a[i]) * t) for i in range(4))


def box(im, x0, y0, x1, y1, color):
    for x in range(max(0, x0), min(S, x1 + 1)):
        for y in range(max(0, y0), min(S, y1 + 1)):
            im.putpixel((x, y), color)


def line_h(im, y, x0, x1, color):
    box(im, x0, y, x1, y, color)


def grain(im, base, dark, seed):
    """Holzmaserung: senkrechte Adern mit ruhigem Rauschen."""
    rnd = random.Random(seed)
    for x in range(S):
        ader = rnd.random() < 0.28
        for y in range(S):
            t = (math.sin(x * 1.7 + y * 0.35 + seed) + 1) / 2
            farbe = mix(base, dark, 0.18 + t * 0.22)
            if ader:
                farbe = mix(farbe, dark, 0.35)
            if rnd.random() < 0.06:
                farbe = mix(farbe, dark, 0.3)
            im.putpixel((x, y), farbe)


def bevel(im, hell=0.30, dunkel=0.35):
    """Oben/links heller, unten/rechts dunkler - gibt Tiefe."""
    weiss = (255, 255, 255, 255)
    schwarz = (0, 0, 0, 255)
    for x in range(S):
        p = im.getpixel((x, 0))
        if p[3]:
            im.putpixel((x, 0), mix(p, weiss, hell))
        p = im.getpixel((x, S - 1))
        if p[3]:
            im.putpixel((x, S - 1), mix(p, schwarz, dunkel))
    for y in range(S):
        p = im.getpixel((0, y))
        if p[3]:
            im.putpixel((0, y), mix(p, weiss, hell * 0.7))
        p = im.getpixel((S - 1, y))
        if p[3]:
            im.putpixel((S - 1, y), mix(p, schwarz, dunkel * 0.7))


def kontur(im, staerke=0.55):
    """
    Legt eine dunkle Linie um die Silhouette.

    Das ist der Unterschied zwischen "bunter Fleck" und "Item": Vanilla
    zeichnet seine Sachen genauso, dadurch heben sie sich vom Hintergrund
    ab und wirken plastisch. Gefärbt wird mit der eigenen Farbe, nicht mit
    Schwarz - sonst sieht alles rußig aus.
    """
    rand = []
    for x in range(S):
        for y in range(S):
            if im.getpixel((x, y))[3]:
                continue
            nachbarn = [im.getpixel((x + dx, y + dy))
                        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))
                        if 0 <= x + dx < S and 0 <= y + dy < S]
            voll = [n for n in nachbarn if n[3]]
            if voll:
                mittel = tuple(sum(n[i] for n in voll) // len(voll) for i in range(3))
                rand.append(((x, y), mix(mittel + (255,), (0, 0, 0, 255), staerke)))
    for stelle, farbe in rand:
        im.putpixel(stelle, farbe)
    return im


def licht(im, staerke=0.22):
    """Licht von oben links, Schatten unten rechts - auf der Silhouette."""
    for x in range(S):
        for y in range(S):
            p = im.getpixel((x, y))
            if not p[3]:
                continue
            oben = im.getpixel((x, y - 1))[3] if y > 0 else 0
            links = im.getpixel((x - 1, y))[3] if x > 0 else 0
            unten = im.getpixel((x, y + 1))[3] if y < S - 1 else 0
            if not oben or not links:
                im.putpixel((x, y), mix(p, (255, 255, 255, 255), staerke))
            elif not unten:
                im.putpixel((x, y), mix(p, (0, 0, 0, 255), staerke * 0.9))
    return im


def save(im, ordner, name):
    ziel = ordner / f"{name}.png"
    ziel.parent.mkdir(parents=True, exist_ok=True)
    im.save(ziel)


def modell(ordner, name, elemente, textur, groesse=(16, 16), display=None):
    daten = {
        "texture_size": list(groesse),
        "textures": {"0": textur, "particle": textur},
        "elements": elemente,
    }
    if display:
        daten["display"] = display
    ziel = ordner / f"{name}.json"
    ziel.parent.mkdir(parents=True, exist_ok=True)
    ziel.write_text(json.dumps(daten, indent=2), encoding="utf-8")


def quader_uv(von, bis, uv):
    """Quader, bei dem alle Seiten denselben Ausschnitt der Textur zeigen.

    Bei einem Auto ist das genau richtig: die Seitenansicht gehört an die
    Seiten, das Dach nimmt den oberen Streifen, die Räder den dunklen.
    """
    faces = {seite: {"uv": list(uv), "texture": "#0"}
             for seite in ("north", "south", "east", "west", "up", "down")}
    return {"from": list(von), "to": list(bis), "faces": faces}


def quader(von, bis, seiten=("north", "south", "east", "west", "up", "down")):
    faces = {}
    for seite in seiten:
        # Grobe, aber ehrliche UV: die Fläche bekommt den passenden Ausschnitt
        if seite in ("up", "down"):
            uv = [von[0], von[2], bis[0], bis[2]]
        elif seite in ("north", "south"):
            uv = [von[0], 16 - bis[1], bis[0], 16 - von[1]]
        else:
            uv = [von[2], 16 - bis[1], bis[2], 16 - von[1]]
        uv = [max(0, min(16, v)) for v in uv]
        faces[seite] = {"uv": uv, "texture": "#0"}
    return {"from": list(von), "to": list(bis), "faces": faces}


# ---------------------------------------------------------------- Möbel

HOLZ = {
    "eiche": ("#B08B4F", "#7C5F32", "#D6B87E"),
    "fichte": ("#7A5B33", "#513A20", "#9C7A4C"),
    "birke": ("#D8CB9A", "#AC9D6C", "#EFE6C0"),
    "akazie": ("#C1662A", "#8E4718", "#E08B4A"),
    "dunkeleiche": ("#4C331C", "#2F1F10", "#6B4B2C"),
}

STOFF = {
    "eiche": "#7C4B4B", "fichte": "#3F5A6B", "birke": "#6B7C4B",
    "akazie": "#7C6B3F", "dunkeleiche": "#5A3F6B",
}


def moebel_textur(holz, art):
    base, dark, light = (hexc(c) for c in HOLZ[holz])
    im = img()
    grain(im, base, dark, seed=sum(ord(c) for c in holz + art))

    fuge = mix(base, dark, 0.85)      # eine Fuge ist fast schwarz
    glanz = mix(base, light, 0.75)    # ein Beschlag blitzt

    def knauf(x, y):
        if not (0 <= x < S and 0 <= y < S):
            return
        box(im, x, y, x + 1, y + 1, mix(base, dark, 0.9))
        im.putpixel((x, y), glanz)

    if art in ("bank", "zaunbank"):
        # Sitzlatten mit deutlichem Spalt dazwischen
        for y in (4, 9, 14):
            line_h(im, y, 0, 15, fuge)
            line_h(im, y - 1, 0, 15, mix(base, light, 0.3))
    elif art == "sessel":
        stoff = hexc(STOFF[holz])
        box(im, 2, 3, 13, 12, mix(stoff, dark, 0.3))
        box(im, 3, 4, 12, 11, stoff)
        box(im, 4, 5, 11, 10, mix(stoff, light, 0.22))
        # Knopf in der Mitte, wie bei einem gepolsterten Sessel
        box(im, 7, 7, 8, 8, mix(stoff, dark, 0.6))
    elif art == "nachttisch":
        line_h(im, 6, 1, 14, fuge)
        box(im, 1, 7, 14, 14, mix(base, dark, 0.18))
        knauf(7, 10)
    elif art == "kommode":
        for y in (2, 7, 12):
            line_h(im, y, 0, 15, fuge)
            line_h(im, y + 1, 0, 15, mix(base, light, 0.28))
            knauf(7, y + 3)
    elif art == "schrank":
        box(im, 7, 0, 8, 15, fuge)
        box(im, 0, 0, 15, 0, mix(base, light, 0.35))
        knauf(5, 7)
        knauf(10, 7)
    elif art == "truhe":
        box(im, 0, 5, 15, 6, fuge)
        box(im, 5, 4, 10, 9, mix(base, dark, 0.35))
        box(im, 6, 5, 9, 8, glanz)
        box(im, 7, 6, 8, 7, dark)
    elif art == "podest":
        box(im, 0, 0, 15, 1, mix(base, light, 0.4))
        box(im, 0, 14, 15, 15, mix(base, dark, 0.5))
        box(im, 2, 3, 13, 12, mix(base, light, 0.2))
        for x, y in ((2, 3), (13, 3), (2, 12), (13, 12)):
            im.putpixel((x, y), fuge)

    bevel(im)
    return im


MOEBEL_FORM = {
    # Art -> Liste von Quadern (von, bis)
    "bank": [((1, 5, 3), (15, 7, 13)), ((1, 7, 11), (15, 15, 13)),
             ((1, 0, 3), (3, 5, 5)), ((13, 0, 3), (15, 5, 5)),
             ((1, 0, 11), (3, 5, 13)), ((13, 0, 11), (15, 5, 13))],
    "zaunbank": [((1, 6, 4), (15, 8, 12)), ((2, 8, 11), (3, 14, 12)),
                 ((13, 8, 11), (14, 14, 12)), ((3, 12, 11), (13, 14, 12)),
                 ((1, 0, 4), (3, 6, 6)), ((13, 0, 4), (15, 6, 6)),
                 ((1, 0, 10), (3, 6, 12)), ((13, 0, 10), (15, 6, 12))],
    "sessel": [((3, 5, 3), (13, 7, 13)), ((3, 7, 11), (13, 14, 13)),
               ((3, 7, 3), (4, 11, 11)), ((12, 7, 3), (13, 11, 11)),
               ((3, 0, 3), (5, 5, 5)), ((11, 0, 3), (13, 5, 5)),
               ((3, 0, 11), (5, 5, 13)), ((11, 0, 11), (13, 5, 13))],
    "nachttisch": [((2, 10, 2), (14, 12, 14)), ((3, 1, 3), (13, 10, 13)),
                   ((2, 0, 2), (4, 1, 4)), ((12, 0, 2), (14, 1, 4)),
                   ((2, 0, 12), (4, 1, 14)), ((12, 0, 12), (14, 1, 14))],
    "kommode": [((1, 0, 2), (15, 13, 14)), ((1, 13, 1), (15, 15, 15))],
    "schrank": [((1, 0, 3), (15, 16, 13))],
    "truhe": [((1, 0, 2), (15, 9, 14)), ((1, 9, 2), (15, 12, 14))],
    "podest": [((0, 0, 0), (16, 4, 16))],
    "tisch": [((0, 12, 0), (16, 15, 16)), ((1, 0, 1), (4, 12, 4)),
              ((12, 0, 1), (15, 12, 4)), ((1, 0, 12), (4, 12, 15)),
              ((12, 0, 12), (15, 12, 15))],
}


def moebel():
    anzahl = 0
    for holz in HOLZ:
        for art in ("bank", "sessel", "nachttisch", "kommode", "schrank",
                    "truhe", "zaunbank", "podest"):
            name = f"{holz}_{art}"
            save(moebel_textur(holz, art), TEX / "block", name)
            form = MOEBEL_FORM.get(art)
            if form:
                modell(MOD / "block", name,
                       [quader(v, b) for v, b in form], f"smp:block/{name}")
            anzahl += 1
    return anzahl


# ------------------------------------------------------- Einzelne Möbel

def sonder_moebel():
    stuecke = {
        "steinbank": ("#8A8A8A", "#5E5E5E", "bank"),
        "stein_tisch": ("#8A8A8A", "#5E5E5E", "tisch"),
        "lampe_klein": ("#E8D48A", "#B79A45", None),
        "lampe_gross": ("#E8D48A", "#B79A45", None),
        "buecherstapel": ("#8B3A3A", "#5C2424", None),
        "teppichrolle": ("#9C4B6B", "#6B3049", "podest"),
        "blumenkasten": ("#6B4A2A", "#452F1A", "truhe"),
        "fass_deko": ("#7A5B33", "#4E3A20", None),
        "amboss_deko": ("#4A4A52", "#26262C", None),
        "kristallsaeule": ("#8FD8E8", "#4A93A8", None),
    }
    for name, (hell, dunkel, form) in stuecke.items():
        base, dark = hexc(hell), hexc(dunkel)
        im = img()
        grain(im, base, dark, seed=sum(ord(c) for c in name))
        if "fass" in name:
            for y in (2, 3, 12, 13):
                line_h(im, y, 0, 15, mix(base, dark, 0.75))
            box(im, 6, 6, 9, 9, mix(base, dark, 0.5))
        if "amboss" in name:
            box(im, 0, 1, 15, 4, mix(base, hexc("#FFFFFF"), 0.18))
            box(im, 4, 5, 11, 10, base)
            box(im, 2, 11, 13, 15, mix(base, dark, 0.4))
        if "teppich" in name:
            for y in range(0, 16, 3):
                line_h(im, y, 0, 15, mix(base, dark, 0.55))
        if "lampe" in name:
            box(im, 4, 4, 11, 11, mix(base, hexc("#FFFFFF"), 0.5))
        if "buecher" in name:
            for y, farbe in ((2, "#3A6B8B"), (6, "#8B3A3A"), (10, "#3A8B4A")):
                box(im, 1, y, 14, y + 2, hexc(farbe))
        if "kristall" in name:
            for x in range(S):
                box(im, x, 0, x, 15, mix(base, hexc("#FFFFFF"),
                                         0.25 + 0.2 * math.sin(x * 0.9)))
        bevel(im)
        save(im, TEX / "block", name)
        if form:
            modell(MOD / "block", name,
                   [quader(v, b) for v, b in MOEBEL_FORM[form]],
                   f"smp:block/{name}")
    return len(stuecke)


# --------------------------------------------- Möbel aus der config.yml

EIGENE_HOELZER = {
    "": ("#B08B4F", "#7C5F32", "#D6B87E"),          # chair, table, ...
    "cherry_": ("#D98A9E", "#A85F72", "#F0B4C2"),   # Kirsche
    "tropic_": ("#C9A961", "#96793C", "#E4CB92"),   # Tropenholz
}

EIGENE_ARTEN = {
    "chair": ("sessel", "sessel"),
    "stool": ("bank", "podest"),
    "table": ("tisch", "tisch"),
    "shelf": ("schrank", "regal"),
    "workbench": ("kommode", "tisch"),
}

MOEBEL_FORM_REGAL = [((1, 0, 11), (15, 16, 13)),   # Rueckwand
                     ((1, 0, 3), (3, 16, 11)),     # linke Seite
                     ((13, 0, 3), (15, 16, 11)),   # rechte Seite
                     ((3, 0, 3), (13, 1, 11)),     # Boden
                     ((3, 15, 3), (13, 16, 11)),   # Deckel
                     ((3, 5, 3), (13, 6, 11)),     # Brett unten
                     ((3, 10, 3), (13, 11, 11))]   # Brett oben


def eigene_moebel():
    """chair, table, shelf, stool, workbench - je dreimal, aus der config.yml."""
    MOEBEL_FORM["regal"] = MOEBEL_FORM_REGAL
    anzahl = 0
    for praefix, farben in EIGENE_HOELZER.items():
        HOLZ[praefix or "eigen"] = farben
        STOFF[praefix or "eigen"] = "#6B5A7C"
        for art, (muster, form) in EIGENE_ARTEN.items():
            name = f"{praefix}{art}"
            save(moebel_textur(praefix or "eigen", muster), TEX / "block", name)
            if form in MOEBEL_FORM:
                modell(MOD / "block", name,
                       [quader(v, b) for v, b in MOEBEL_FORM[form]],
                       f"smp:block/{name}")
            anzahl += 1
    # easel: eine Staffelei
    save(moebel_textur("eigen", "podest"), TEX / "block", "easel")
    modell(MOD / "block", "easel", [
        quader((7, 0, 2), (9, 16, 4)), quader((2, 0, 10), (4, 14, 12)),
        quader((12, 0, 10), (14, 14, 12)), quader((2, 8, 3), (14, 15, 10)),
    ], "smp:block/easel")
    return anzahl + 1


# ------------------------------------------------------- Erze und Steine

ERZ = {
    # id: (Grundstein, Ader, Glanz)
    "ruby_ore": ("#7E7E7E", "#C0223A", "#FF6B7E"),
    "sapphire_ore": ("#7E7E7E", "#2246C0", "#6B8CFF"),
    "ruby_block": ("#C0223A", "#8A1428", "#FF6B7E"),
    "sapphire_block": ("#2246C0", "#16308A", "#6B8CFF"),
    "marble": ("#E4E2DC", "#C2BFB6", "#FFFFFF"),
    "dark_marble": ("#3A3A42", "#26262C", "#5E5E6B"),
    "neon_lamp": ("#2A2A32", "#16161C", "#7BE8FF"),
    "coin_pile": ("#8A6A2A", "#5E4718", "#F0D060"),
}


def erz_textur(base_hex, ader_hex, glanz_hex, seed, block=False):
    """Ein Stein mit Adern - oder ein voller Block, wenn block=True."""
    base, ader, glanz = hexc(base_hex), hexc(ader_hex), hexc(glanz_hex)
    im = img()
    rnd = random.Random(seed)
    for x in range(S):
        for y in range(S):
            t = rnd.random()
            im.putpixel((x, y), mix(base, ader, 0.05 + t * 0.20))
    if block:
        # Voller Block: eingelassene Facetten
        for _ in range(9):
            x, y = rnd.randrange(1, 14), rnd.randrange(1, 14)
            box(im, x, y, x + 1, y + 1, mix(base, glanz, 0.45))
            im.putpixel((x, y), glanz)
    else:
        # Erz: ein paar Nester mit Glanzpunkt
        for _ in range(5):
            x, y = rnd.randrange(2, 13), rnd.randrange(2, 13)
            box(im, x, y, x + 1, y + 1, ader)
            im.putpixel((x, y), glanz)
            if rnd.random() < 0.6:
                im.putpixel((x + 1, y + 1), mix(ader, glanz, 0.4))
    bevel(im, 0.22, 0.28)
    return im


def marmor_textur(base_hex, ader_hex, glanz_hex, seed):
    base, ader, glanz = hexc(base_hex), hexc(ader_hex), hexc(glanz_hex)
    im = img()
    rnd = random.Random(seed)
    for x in range(S):
        for y in range(S):
            t = (math.sin(x * 0.5 + y * 0.2) + 1) / 2
            im.putpixel((x, y), mix(base, glanz, t * 0.18))
    # Zwei geschwungene Adern
    for start in (3, 10):
        y = start
        for x in range(S):
            y = max(0, min(S - 1, y + rnd.choice((-1, 0, 0, 1))))
            im.putpixel((x, y), mix(base, ader, 0.75))
            if 0 <= y + 1 < S:
                im.putpixel((x, y + 1), mix(base, ader, 0.35))
    bevel(im, 0.20, 0.24)
    return im


def erze():
    for name, (b, a, g) in ERZ.items():
        seed = sum(ord(c) for c in name)
        if "marble" in name:
            im = marmor_textur(b, a, g, seed)
        elif name == "neon_lamp":
            im = erz_textur(b, a, g, seed, block=True)
            box(im, 3, 3, 12, 12, hexc(g))
            box(im, 5, 5, 10, 10, mix(hexc(g), hexc("#FFFFFF"), 0.5))
        else:
            im = erz_textur(b, a, g, seed, block="block" in name or "pile" in name)
        save(im, TEX / "block", name)
    return len(ERZ)


# ---------------------------------------------------------------- Items

FAHRZEUG_FARBEN = {
    "auto_sport": ("#C22B2B", "#7A1616", "#2A2A30"),
    "auto_roadster": ("#E0A020", "#9C6C10", "#2A2A30"),
    "auto_muscle": ("#8B1A1A", "#561010", "#2A2A30"),
    "auto_renn": ("#E8D020", "#A08C10", "#2A2A30"),
    "auto_hyper": ("#A050E0", "#6A2F9C", "#2A2A30"),
    "auto_oldtimer": ("#2F6B5A", "#1C443A", "#3A2A1A"),
    "auto_polizei": ("#2A4FA0", "#16306B", "#2A2A30"),
    "auto_gelaende": ("#4A6B32", "#2F4520", "#2A2A30"),
    "jet_renn": ("#B8C4D0", "#7A8794", "#3A4650"),
    "jet_kampf": ("#6B7280", "#454A54", "#2A2E36"),
    "jet_passagier": ("#E4E8EC", "#A8AEB6", "#2A4FA0"),
    "flugzeug_propeller": ("#E0C020", "#A08C10", "#7A5B33"),
    "flugzeug_doppeldecker": ("#C25A2B", "#7A3416", "#7A5B33"),
    "flugzeug_fracht": ("#4A6B32", "#2F4520", "#3A4650"),
    "heli_leicht": ("#2F8B9C", "#1C5A66", "#2A2E36"),
    "heli_rettung": ("#C22B2B", "#7A1616", "#E4E8EC"),
    "zug_lok": ("#4A4A52", "#26262C", "#8B3A3A"),
    "auto_stier": ("#C8E020", "#8A9C10", "#2A2A30"),
    "auto_veloce": ("#2A3F9C", "#16265E", "#D8DCE4"),
    # Keil-Familie: Mittelmotor, scharfe Kante, grosser Heckfluegel
    "auto_aventador": ("#E8C41A", "#A08610", "#2A2A30"),
    "auto_huracan": ("#3FA83A", "#1F6B1C", "#2A2A30"),
    "auto_revuelto": ("#D83A20", "#8F2010", "#2A2A30"),
    "auto_countach": ("#E8E8EC", "#A8AEB6", "#2A2A30"),
    "auto_diablo": ("#7A3AC8", "#4A1E80", "#2A2A30"),
    # Rundheck-Familie: Heckmotor, kurzer Radstand, Entenbuerzel
    "auto_carrera": ("#C8CCD4", "#8A8F98", "#2A3A50"),
    "auto_turbo_s": ("#1E3A78", "#12234A", "#D8DCE4"),
    "auto_gt3": ("#E87A18", "#9C4E0C", "#E4E8EC"),
    "auto_taycan": ("#20B8C8", "#127785", "#E4E8EC"),
    "auto_neunelf": ("#EDEDF0", "#A8AEB6", "#E85A18"),
    # Breitbau-Familie: sehr lang, sehr breit, Hufeisengrill
    "auto_chiron": ("#1F5FC8", "#123A80", "#0E1420"),
    "auto_veyron": ("#3A3A44", "#1C1C22", "#B02020"),
    "auto_divo": ("#5AC8E0", "#2F7F94", "#1A1E26"),
    "auto_bolide": ("#26262E", "#131318", "#E8D020"),
    "auto_tourbillon": ("#D0D8E4", "#8A94A4", "#2A4FA0"),
    "boot_ruder": ("#A87A3A", "#6B4A1C", "#D8B070"),
    "boot_motor": ("#3A9CB8", "#1F5E70", "#E4E8EC"),
    "boot_yacht": ("#E8E8EC", "#A8AEB6", "#2A4FA0"),
}

# Die drei Supersportwagen-Familien. Jede hat eine eigene Silhouette und
# einen eigenen Aufbau - sonst waeren fuenfzehn Autos nur fuenfzehn Farben.
KEIL_FAMILIE = frozenset((
    "auto_stier", "auto_aventador", "auto_huracan",
    "auto_revuelto", "auto_countach", "auto_diablo",
))
RUNDHECK_FAMILIE = frozenset((
    "auto_carrera", "auto_turbo_s", "auto_gt3",
    "auto_taycan", "auto_neunelf",
))
BREITBAU_FAMILIE = frozenset((
    "auto_veloce", "auto_chiron", "auto_veyron",
    "auto_divo", "auto_bolide", "auto_tourbillon",
))

# Seitenansichten: . durchsichtig, K Karosserie, D dunkel, F Fenster/Akzent
#
# Alle Autos stehen auf denselben drei Zeilen Rad (9 bis 11) und haben die
# Nase rechts. Ein Rad ist 3x3 mit einer helleren Felge in der Mitte - das
# liest sich auch bei 16 Pixeln noch als Rad und nicht als Tropfen.
AUTO = """
................
................
................
.....KKKKKK.....
....KKFFFFKK....
...KKKKKKKKKKK..
..KKKKKKKKKKKKK.
..KKKKKKKKKKKKKK
..KKKKKKKKKKKKKK
..DDDKKKKKKDDDK.
..DFD......DFD..
..DDD......DDD..
................
................
................
................
"""


# Der Keil: spitze Nase rechts, gekapptes Heck links, grosser Fluegel.
KEIL = """
................
................
................
................
.DDDDD..........
.KKKKKKKK.......
..KKKFFFKKK.....
..KKKKKKKKKKKK..
..KKKKKKKKKKKKKK
..DDDKKKKKKDDDK.
..DFD......DFD..
..DDD......DDD..
................
................
................
................
"""


# Rundheck: Heckmotor, runder Bug, das Dach faellt nach hinten weg und
# endet in einem kleinen Buerzel.
CARRERA = """
................
................
................
.......KKKKK....
.....KKFFFFFKK..
.DDKKKKKKKKKKKK.
.KKKKKKKKKKKKKKK
.KKKKKKKKKKKKKKK
.KKKKKKKKKKKKKK.
..DDDKKKKKKDDDK.
..DFD......DFD..
..DDD......DDD..
................
................
................
................
"""


# Breitbau: sehr lang und flach, untere Haelfte in der zweiten Farbe -
# das ist die Zweifarb-Linie, an der man den Wagen von weitem erkennt.
ROYALE = """
................
................
................
................
......KKKKKK....
....KKFFFFFKKK..
..KKKKKKKKKKKKK.
.KKKKKKKKKKKKKKK
.FFFFFFFFFFFFFFF
..DDDFFFFFFDDDF.
..DFD......DFD..
..DDD......DDD..
................
................
................
................
"""


JET = """
................
................
.......K........
.......KK.......
.......KK.......
....KKKKKKKK....
...FKKKKKKKKF...
...KKKKKKKKKK...
.......KK.......
.......KK.......
......DKKD......
.....DD..DD.....
................
................
................
................
"""

PROP = """
................
................
.D..............
.D....KKKKK.....
.D...KKFFKKK....
.DKKKKKKKKKKKD..
.D...KKKKKK.KD..
.D....KKKK......
......KKKK......
.....DDDDDD.....
.......DD.......
................
................
................
................
................
"""

DOPPEL = """
................
................
..KKKKKKKKKKK...
..KKKKKKKKKKK...
.......KK.......
.D...KKKKKKK....
.D..KKFFKKKKKD..
.D...KKKKKKK.D..
..KKKKKKKKKKK...
..KKKKKKKKKKK...
.....DD..DD.....
................
................
................
................
................
"""

FRACHT = """
................
................
...KKKKKKKKKK...
..KKKKKKKKKKKD..
.KKFFKKKKKKKKD..
.KKKKKKKKKKKKK..
.KKKKKKKKKKKK...
..DDKKKKKKDD....
...D.DDDD.D.....
....DD..DD......
................
................
................
................
................
................
"""

HELI = """
................
..DDDDDDDDDDDD..
.......D........
.....KKKKKK.....
....KKFFFFKK....
...KKKKKKKKKKD..
...KKKKKKKKKKDD.
....KKKKKKKK....
.....D....D.....
....DDD..DDD....
................
................
................
................
................
................
"""

ZUG = """
................
...D............
...D............
..DDD...........
..KKKKKKKKKKK...
..KKKKKKKKKKK...
..KKKKFFFKKKK...
..KKKKFFFKKKK...
..KKKKKKKKKKK...
..DDDDDDDDDDD...
...DD..DD..DD...
...DD..DD..DD...
................
................
................
................
"""


def aus_form(form, palette):
    im = img()
    zeilen = [z for z in form.strip("\n").split("\n")]
    for y, zeile in enumerate(zeilen[:S]):
        for x, zeichen in enumerate(zeile[:S]):
            if zeichen in palette:
                im.putpixel((x, y), palette[zeichen])
    return im


def koerper(name):
    """
    Der Körper eines Fahrzeugs, aus wenigen Quadern.

    Die UV-Ausschnitte zeigen auf die passende Stelle der Seitenansicht:
    der Aufbau nimmt den hellen Streifen, die Räder den dunklen darunter.
    Dadurch braucht jedes Fahrzeug nur eine einzige 16x16-Textur.
    """
    hell = [2, 5, 14, 9]      # Karosserie - die Flanke zwischen Dach und Rad
    dunkel = [2, 9, 5, 12]    # Räder, Fahrwerk, Streben - das hintere Rad
    dach = [4, 3, 12, 6]      # Fenster und Aufbau - Dach und Scheiben

    # Die drei Familien. Die Quader stossen aneinander, statt sich zu
    # ueberlappen: zwei deckungsgleiche Flaechen im selben Punkt flackern
    # im Spiel gegeneinander. Nase ist z=0, das Heck z=16.
    if name in KEIL_FAMILIE:
        # Der Keil: Wanne, dann eine Schulter, die nach hinten hoeher wird,
        # Kanzel weit hinten und ein Fluegel auf zwei Stuetzen.
        return [
            quader_uv((2, 2, 0), (14, 5, 16), hell),      # flache Wanne
            quader_uv((3, 5, 5), (13, 7, 16), hell),      # Schulter nach hinten
            quader_uv((4, 7, 7), (12, 10, 13), dach),     # Kanzel
            quader_uv((6, 7, 13), (10, 9, 15), dunkel),   # Fluegelstuetze
            quader_uv((1, 9, 13), (15, 10, 16), dunkel),  # Heckfluegel
            quader_uv((2, 0, 2), (5, 2, 5), dunkel),      # vier flache Raeder
            quader_uv((11, 0, 2), (14, 2, 5), dunkel),
            quader_uv((2, 0, 11), (5, 2, 14), dunkel),
            quader_uv((11, 0, 11), (14, 2, 14), dunkel),
        ]
    if name in RUNDHECK_FAMILIE:
        # Rundheck: kurzer Radstand, ausgestellte Kotfluegel, das Dach
        # faellt nach hinten weg und endet in einem kleinen Buerzel.
        return [
            quader_uv((3, 3, 1), (13, 6, 15), hell),      # Wanne, schmaler
            quader_uv((2, 6, 2), (14, 8, 14), hell),      # ausgestellte Kotfluegel
            quader_uv((4, 8, 5), (12, 11, 12), dach),     # Fastback-Dach
            quader_uv((4, 8, 12), (12, 9, 14), dunkel),   # Entenbuerzel
            quader_uv((2, 0, 2), (5, 3, 5), dunkel),      # vier Raeder
            quader_uv((11, 0, 2), (14, 3, 5), dunkel),
            quader_uv((2, 0, 10), (5, 3, 13), dunkel),
            quader_uv((11, 0, 10), (14, 3, 13), dunkel),
        ]
    if name in BREITBAU_FAMILIE:
        # Breitbau: nutzt den Block ganz aus, flach wie ein Brett, mit
        # ausfahrbarem Heckspoiler statt Fluegel.
        return [
            quader_uv((1, 2, 0), (15, 6, 16), hell),      # sehr breite Wanne
            quader_uv((4, 6, 4), (12, 9, 12), dach),      # flache Kanzel
            quader_uv((7, 6, 12), (9, 8, 16), dunkel),    # Mittelfinne hinten
            quader_uv((2, 8, 13), (14, 9, 15), dunkel),   # Heckspoiler
            quader_uv((1, 0, 2), (4, 2, 6), dunkel),      # vier breite Raeder
            quader_uv((12, 0, 2), (15, 2, 6), dunkel),
            quader_uv((1, 0, 10), (4, 2, 14), dunkel),
            quader_uv((12, 0, 10), (15, 2, 14), dunkel),
        ]
    if name.startswith("auto_"):
        # Lang in Z - das ist die Fahrtrichtung. Quer gebaut wuerde das Auto
        # seitwaerts fahren.
        return [
            quader_uv((3, 3, 1), (13, 8, 15), hell),      # Wanne
            quader_uv((4, 8, 4), (12, 11, 12), dach),     # Kabine
            quader_uv((2, 0, 2), (5, 3, 5), dunkel),      # vier Räder
            quader_uv((11, 0, 2), (14, 3, 5), dunkel),
            quader_uv((2, 0, 11), (5, 3, 14), dunkel),
            quader_uv((11, 0, 11), (14, 3, 14), dunkel),
        ]
    if name.startswith("heli_"):
        # Der Rotor ist ein eigenes Teil - nur so kann er sich drehen
        return [
            quader_uv((4, 3, 1), (12, 10, 11), hell),     # Kanzel
            quader_uv((6, 5, 11), (10, 8, 16), hell),     # Heckausleger
            quader_uv((7, 10, 7), (9, 12, 9), dunkel),    # Rotorkopf
            quader_uv((7, 8, 14), (9, 12, 16), dunkel),   # Heckrotor
            quader_uv((5, 0, 2), (6, 3, 10), dunkel),     # Kufen
            quader_uv((10, 0, 2), (11, 3, 10), dunkel),
        ]
    if name.startswith("boot_"):
        return [
            quader_uv((3, 2, 0), (13, 6, 16), hell),      # Rumpf
            quader_uv((4, 6, 1), (12, 7, 15), dach),      # Deck
            quader_uv((5, 7, 4), (11, 11, 10), dach),     # Aufbau
            quader_uv((7, 11, 6), (9, 14, 8), dunkel),    # Mast
        ]
    if name == "zug_lok":
        return [
            quader_uv((3, 3, 0), (13, 11, 16), hell),     # Kessel, laengs
            quader_uv((6, 11, 1), (10, 15, 5), dunkel),   # Schornstein vorn
            quader_uv((3, 0, 0), (13, 3, 16), dunkel),    # Fahrwerk
        ]
    # Flugzeuge und Jets: Rumpf, Fluegel, Leitwerk
    lang = 15 if "passagier" in name or "fracht" in name else 13
    return [
        quader_uv((6, 4, 1), (10, 9, lang), hell),        # Rumpf
        quader_uv((0, 5, 5), (16, 6, 10), hell),          # Tragflaechen
        quader_uv((5, 5, lang - 3), (11, 6, lang + 1), hell),  # Hoehenruder
        quader_uv((7, 9, lang - 3), (9, 13, lang), dunkel),  # Seitenruder
        quader_uv((3, 3, 6), (5, 5, 9), dunkel),          # Triebwerke
        quader_uv((11, 3, 6), (13, 5, 9), dunkel),
    ]


def fahrzeug_items():
    for name, (hell, dunkel, akzent) in FAHRZEUG_FARBEN.items():
        if name in KEIL_FAMILIE:
            form = KEIL
        elif name in RUNDHECK_FAMILIE:
            form = CARRERA
        elif name in BREITBAU_FAMILIE:
            form = ROYALE
        elif name.startswith("auto_"):
            form = AUTO
        elif name.startswith("heli_"):
            form = HELI
        elif name.startswith("jet_"):
            form = JET
        elif name == "zug_lok":
            form = ZUG
        elif "doppeldecker" in name:
            form = DOPPEL
        elif "fracht" in name:
            form = FRACHT
        elif name.startswith("boot_"):
            form = BOOT
        else:
            form = PROP
        palette = {"K": hexc(hell), "D": hexc(dunkel), "F": hexc(akzent)}
        im = licht(aus_form(form, palette))
        kontur(im)
        save(im, TEX / "item", name)

        modell(MOD / "item", name, koerper(name), f"smp:item/{name}",
               display={"thirdperson_righthand": {
                   "rotation": [0, 90, 0], "translation": [0, 1, 0],
                   "scale": [0.45, 0.45, 0.45]},
                   "gui": {"rotation": [30, 225, 0], "scale": [0.5, 0.5, 0.5]}})
    return len(FAHRZEUG_FARBEN)


BOOT = """
................
................
................
................
......DD........
.....DDDD.......
....DDDDDD......
.KKKKKKKKKKKKK..
.KFFFFFFFFFFFK..
.KKKKKKKKKKKKK..
..KKKKKKKKKKK...
...KKKKKKKKK....
....DDDDDDD.....
................
................
................
"""


SCHIRM = """
................
.....KKKKKK.....
...KKKKKKKKKK...
..KKKKKKKKKKKK..
.KKKKKKKKKKKKKK.
.KKFFKKKKKKFFKK.
..KK.K.KK.K.KK..
...D..D..D..D...
....D.D..D.D....
.....DD..DD.....
......D..D......
.......DD.......
.......DD.......
................
................
................
"""

PISTOLE = """
................
................
................
....KKKKKKKK....
....KKKKKKKKD...
....KKD.........
....KKD.........
...KKKD.........
...KKD..........
...KKD..........
....D...........
................
................
................
................
................
"""

FLINTE = """
................
................
..KKKKKKKKKKKD..
..KKKKKKKKKKKD..
..DDDKKD........
.....KKD........
.....KKD........
....KKKD........
....KKD.........
.....D..........
................
................
................
................
................
................
"""

WERFER = """
................
................
................
..KKKKKKKKKKKK..
..KFFKKKKKKKKK..
..KKKKKKKKKKKK..
..DDDDKKDDDDDD..
......KKD.......
.....KKKD.......
.....KKD........
......D.........
................
................
................
................
................
"""

KUGEL = """
................
................
................
................
......KK........
.....KKKK.......
.....KFFK.......
.....KKKK.......
......DD........
................
................
................
................
................
................
................
"""


ROTOR = """
................
.......DD.......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
DDDDDDDKKDDDDDDD
DDDDDDDKKDDDDDDD
.......DD.......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
................
"""


def rotorblatt():
    """Das drehende Blatt - ein flaches Kreuz, damit es von oben gut aussieht."""
    palette = {"K": hexc("#3A3E46"), "D": hexc("#2A2E36")}
    save(kontur(licht(aus_form(ROTOR, palette))), TEX / "item", "rotorblatt")
    modell(MOD / "item", "rotorblatt", [
        quader_uv((0, 7.5, 7), (16, 8.5, 9), [0, 7, 16, 9]),
        quader_uv((7, 7.5, 0), (9, 8.5, 7), [7, 0, 9, 7]),
        quader_uv((7, 7.5, 9), (9, 8.5, 16), [7, 9, 9, 16]),
    ], "smp:item/rotorblatt")
    return 1


def sonstige_items():
    stuecke = {
        "fallschirm": (SCHIRM, "#E8E8EC", "#9C9CA4", "#C22B2B"),
        "pistole": (PISTOLE, "#4A4A52", "#26262C", "#8B6B3A"),
        "schrotflinte": (FLINTE, "#5A4A3A", "#332720", "#4A4A52"),
        "raketenwerfer": (WERFER, "#3A4A3A", "#1F2A1F", "#C22B2B"),
        "kugel": (KUGEL, "#C8B060", "#8B7530", "#E8D890"),
    }
    for name, (form, hell, dunkel, akzent) in stuecke.items():
        palette = {"K": hexc(hell), "D": hexc(dunkel), "F": hexc(akzent)}
        im = licht(aus_form(form, palette))
        save(kontur(im), TEX / "item", name)
    return len(stuecke)


# ------------------------------------------ Alles Übrige aus der config

# MiniMessage-Farben, damit ein "<red>Rubinschwert" auch rot wird
FARBNAMEN = {
    "black": "#2A2A2A", "dark_blue": "#2B3FA0", "dark_green": "#2F7A3F",
    "dark_aqua": "#2F9C9C", "dark_red": "#9C2222", "dark_purple": "#7A2F9C",
    "gold": "#E0A020", "gray": "#A0A0A8", "dark_gray": "#5A5A62",
    "blue": "#4A6BE0", "green": "#4AC24A", "aqua": "#4AD8E0", "red": "#E04A4A",
    "light_purple": "#E04AD8", "yellow": "#E8D84A", "white": "#F0F0F4",
}

# Grundform je Material - so bekommt jedes Item eine passende Silhouette
FORMEN = {
    "SWORD": """
................
..............K.
.............KK.
............KKK.
...........KKK..
..........KKK...
.........KKK....
........KKK.....
.......KKK......
......KKK.......
.....KKK........
..D.KKK.........
..DDKK..........
.DDDD...........
.DD.D...........
D...............
""",
    "PICKAXE": """
................
....KKKKKKKK....
...KKKKKKKKKK...
...KK......KK...
...K...DD...K...
.......DD.......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
................
................
""",
    "AXE": """
................
....KKKK........
...KKKKKK.......
...KKKKKKD......
...KKKKKDD......
....KKK.DD......
.....K..DD......
........DD......
........DD......
........DD......
........DD......
........DD......
........DD......
........DD......
................
................
""",
    "SHOVEL": """
................
......KKKK......
.....KKKKKK.....
.....KKKKKK.....
.....KKKKKK.....
......KKKK......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
.......DD.......
................
................
""",
    "POTION": """
................
.......DD.......
.......DD.......
......DDDD......
.....DKKKKD.....
....DKKKKKKD....
...DKKKKKKKKD...
...DKKKKKKKKD...
...DKFFFFFFKD...
...DKFFFFFFKD...
...DKFFFFFFKD...
....DKFFFFKD....
.....DDDDDD.....
................
................
................
""",
    "GEM": """
................
................
......KKKK......
.....KFFFFK.....
....KFFFFFFK....
....KFFFFFFK....
....KKFFFFKK....
.....KKFFKK.....
......KKKK......
.......KK.......
................
................
................
................
................
................
""",
    "FRUIT": """
................
.......D........
......DD........
.....KKKKK......
....KKFKKKK.....
...KKKKKKKKK....
...KKKKKKKKK....
...KKKKKKKKK....
....KKKKKKK.....
.....KKKKK......
......KKK.......
................
................
................
................
................
""",
    "DUST": """
................
................
....K...K.......
......K....K....
...K...KK.......
.....KK...K.....
..K....K...K....
....KK...K......
.K....KK....K...
...K....K.......
.....K....K.....
..K....K........
................
................
................
................
""",
    "KEY": """
................
................
.....KKKK.......
....KK..KK......
....K.DD.K......
....KK..KK......
.....KKKK.......
......KK........
......KK........
......KK........
......KKK.......
......KK........
......KKK.......
......KK........
................
................
""",
    "COIN": """
................
................
......KKKK......
.....KFFFFK.....
....KFFKKFFK....
....KFKFFKFK....
....KFKFFKFK....
....KFFKKFFK....
.....KFFFFK.....
......KKKK......
................
................
................
................
................
................
""",
    "HEART": """
................
................
...KK.....KK....
..KFFK...KFFK...
.KFFFFK.KFFFFK..
.KFFFFFKFFFFFK..
.KFFFFFFFFFFFK..
..KFFFFFFFFFK...
...KFFFFFFFK....
....KFFFFFK.....
.....KFFFK......
......KFK.......
.......K........
................
................
................
""",
    "TOTEM": """
................
.......K........
......KKK.......
.....KFFFK......
.....KFKFK......
.....KFFFK......
......KKK.......
....KKKKKKK.....
...KK.KKK.KK....
...K..KKK..K....
......KKK.......
......KKK.......
.....KKKKK......
................
................
................
""",
    "SHARD": """
................
................
.........K......
........KFK.....
.......KFFK.....
......KFFFK.....
.....KFFFK......
....KFFFK.......
....KFFK........
...KFFK.........
...KFK..........
...KK...........
................
................
................
................
""",
    "SCROLL": """
................
................
..DKKKKKKKKKD...
..DKFFFFFFFKD...
..DKFDDDDFFKD...
..DKFFFFFFFKD...
..DKFDDDDDFKD...
..DKFFFFFFFKD...
..DKFDDDFFFKD...
..DKFFFFFFFKD...
..DKKKKKKKKKD...
................
................
................
................
................
""",
    "BOMB": """
................
................
.........DD.....
........DD......
.......DD.......
.....KKKK.......
....KKKKKK......
...KKKFKKKK.....
...KKKKKKKK.....
...KKKKKKKK.....
....KKKKKK......
.....KKKK.......
................
................
................
................
""",
    "RUNE": """
................
................
...KKKKKKKKK....
...KFFFFFFFK....
...KFDFFFDFK....
...KFFDFDFFK....
...KFFFDFFFK....
...KFFDFDFFK....
...KFDFFFDFK....
...KFFFFFFFK....
...KKKKKKKKK....
................
................
................
................
................
""",
    "AMULETT": """
................
....DDDDDDD.....
....D.....D.....
...D.......D....
...D.......D....
....D.....D.....
.....KKKKK......
....KFFFFFK.....
....KFFFFFK.....
....KFFFFFK.....
.....KKKKK......
................
................
................
................
................
""",
    "HAMMER": """
................
................
...KKKKKKKK.....
..KKKKKKKKKK....
..KKKKKKKKKK....
...KKKKKKKK.....
......DD........
......DD........
......DD........
......DD........
......DD........
......DD........
......DD........
......DD........
................
................
""",
    "STICK": """
................
..............D.
.............DD.
............DD..
...........DD...
..........DD....
.........DD.....
........DD......
.......DD.......
......DD........
.....DD.........
....DD..........
...DD...........
..DD............
................
................
""",
    "PLATE": """
................
................
...KKKKKKKKKK...
..KKFFFFFFFFKK..
..KKFFFFFFFFKK..
..KKFFFFFFFFKK..
..KKFFFFFFFFKK..
..KKFFFFFFFFKK..
..KKFFFFFFFFKK..
...KKKKKKKKKK...
................
................
................
................
................
................
""",
}


SCHLUESSELWORTE = (
    ("kirsch", "FRUIT"), ("kokos", "FRUIT"), ("mango", "FRUIT"),
    ("banane", "FRUIT"), ("ananas", "FRUIT"), ("frucht", "FRUIT"),
    ("beere", "FRUIT"), ("apfel", "FRUIT"),
    ("potion", "POTION"), ("trank", "POTION"), ("flasche", "POTION"),
    ("elixier", "POTION"), ("healer", "POTION"), ("springer", "POTION"),
    ("schluessel", "KEY"), ("key", "KEY"),
    ("coin", "COIN"), ("muenze", "COIN"), ("taler", "COIN"),
    ("heart", "HEART"), ("herz", "HEART"),
    ("totem", "TOTEM"),
    ("shard", "SHARD"), ("splitter", "SHARD"), ("kristall", "SHARD"),
    ("scroll", "SCROLL"), ("rolle", "SCROLL"), ("voucher", "SCROLL"),
    ("gutschein", "SCROLL"), ("karte", "SCROLL"),
    ("bomb", "BOMB"), ("granate", "BOMB"),
    ("rune", "RUNE"), ("amulett", "AMULETT"), ("anhaenger", "AMULETT"),
    ("hammer", "HAMMER"), ("dust", "DUST"), ("staub", "DUST"),
    ("stick", "STICK"), ("stock", "STICK"), ("zweig", "STICK"),
    ("handy", "RUNE"), ("bluete", "FRUIT"),
)


def art_von(material, id_):
    # Der Name sagt mehr als das Material: viele Items benutzen dieselbe
    # Pferderuestung als Traeger und waeren sonst alle gleich.
    klein = id_.lower()
    for wort, form in SCHLUESSELWORTE:
        if wort in klein:
            return form
    for teil, form in (("SWORD", "SWORD"), ("PICKAXE", "PICKAXE"), ("AXE", "AXE"),
                       ("SHOVEL", "SHOVEL"), ("HOE", "SHOVEL")):
        if teil in material:
            return form
    if "POTION" in material or "BOTTLE" in material:
        return "POTION"
    if material in ("AMETHYST_SHARD", "DIAMOND", "EMERALD", "QUARTZ", "PRISMARINE_CRYSTALS"):
        return "GEM"
    if material in ("APPLE", "SWEET_BERRIES", "MELON_SLICE", "CARROT", "POTATO",
                    "GOLDEN_APPLE", "BREAD", "COOKIE", "PUMPKIN_PIE"):
        return "FRUIT"
    if "DUST" in material or "POWDER" in material:
        return "DUST"
    return "PLATE"


def farbe_aus_namen(name, id_):
    import re as _re
    treffer = _re.findall(r"<(#[0-9a-fA-F]{6}|[a-z_]+)>", name or "")
    for t in treffer:
        if t.startswith("#"):
            return t
        if t in FARBNAMEN:
            return FARBNAMEN[t]
    # Keine Farbe im Namen: eine aus der Id ableiten, aber immer dieselbe
    h = sum(ord(c) * (i + 3) for i, c in enumerate(id_))
    return list(FARBNAMEN.values())[h % len(FARBNAMEN)]


def restliche_items(config_pfad):
    """Zeichnet alles aus der config.yml, was noch keine Textur hat."""
    import yaml
    daten = yaml.safe_load(open(config_pfad, encoding="utf-8"))
    da = {p.stem for p in (TEX / "item").glob("*.png")}
    anzahl = 0
    for id_, e in (daten.get("items") or {}).items():
        if id_ in da:
            continue
        material = str(e.get("material", "PAPER")).upper()
        art = art_von(material, id_)
        form = FORMEN[art]
        haupt = hexc(farbe_aus_namen(e.get("name", ""), id_))
        palette = {
            "K": haupt,
            "D": mix(haupt, (0, 0, 0, 255), 0.45),
            "F": mix(haupt, (255, 255, 255, 255), 0.35),
        }
        im = licht(aus_form(form, palette))
        # Streupulver bleibt ohne Kontur, sonst verklebt es zu einem Fleck
        if art != "DUST":
            kontur(im)
        save(im, TEX / "item", id_)
        anzahl += 1
    return anzahl


# ---------------------------------------------------------------- Lauf

def pruefe_modelle():
    """
    Sucht Stellen, an denen zwei Quader eines Modells im Spiel flackern.

    Das passiert genau dann, wenn sie sich überschneiden **und** in
    derselben Ebene eine Fläche haben: Minecraft weiß dann nicht, welche
    vorne liegt, und zeigt bei jeder Kopfbewegung eine andere. Ein Flügel,
    der quer durch einen Rumpf geht, ist dagegen völlig in Ordnung - da
    liegt keine Fläche auf einer anderen.

    Aneinanderstoßen ist erlaubt, deshalb `<` und nicht `<=`.
    """
    def flackert(a, b):
        ueber = [(max(a["from"][i], b["from"][i]), min(a["to"][i], b["to"][i]))
                 for i in range(3)]
        if not all(lo < hi for lo, hi in ueber):
            return None
        for k in range(3):
            for seite in ("from", "to"):
                if a[seite][k] == b[seite][k] and all(
                        ueber[i][0] < ueber[i][1] for i in range(3) if i != k):
                    return f"{'xyz'[k]} = {a[seite][k]}"
        return None

    beanstandet = []
    dateien = sorted(MOD.rglob("*.json"))
    for datei in dateien:
        teile = json.loads(datei.read_text(encoding="utf-8")).get("elements", [])
        for i, eins in enumerate(teile):
            if any(v < -16 or v > 32 for v in eins["from"] + eins["to"]):
                beanstandet.append(f"{datei.name}: Quader {i} liegt ausserhalb")
            for j in range(i + 1, len(teile)):
                wo = flackert(eins, teile[j])
                if wo:
                    beanstandet.append(f"{datei.name}: Quader {i} und {j} "
                                       f"flackern bei {wo}")
    for zeile in beanstandet:
        print("  ! " + zeile)
    print(f"{len(dateien)} Modelle geprüft, "
          f"{len(beanstandet) or 'keine'} Beanstandungen")
    return not beanstandet


if __name__ == "__main__":
    a = moebel()
    b = sonder_moebel() + erze() + eigene_moebel()
    c = fahrzeug_items()
    d = sonstige_items() + rotorblatt()
    e = restliche_items(ROOT / "src/main/resources/config.yml")
    print(f"{e} weitere Items aus der config.yml gezeichnet")
    print(f"{a + b} Möbel, {c} Fahrzeuge, {d} weitere Items")
    print(f"Texturen: {len(list((TEX / 'block').glob('*.png')))} Block, "
          f"{len(list((TEX / 'item').glob('*.png')))} Item")
    print(f"Modelle:  {len(list((MOD / 'block').glob('*.json')))} Block, "
          f"{len(list((MOD / 'item').glob('*.json')))} Item")
    raise SystemExit(0 if pruefe_modelle() else 1)
