#!/usr/bin/env python3
"""Erzeugt die 16x16-Item-Texturen fuer beide Resourcepacks.

Keine Abhaengigkeiten - die PNGs werden direkt geschrieben (zlib gehoert zur
Standardbibliothek). Die Pixelbilder stehen als ASCII-Art in ART, damit man sie
im Diff lesen und bearbeiten kann.

Aufruf:  python3 tools/generate_textures.py
Ziel:    resourcepack/java/assets/lemonpvp/textures/item/<id>.png
         resourcepack/bedrock/textures/items/<id>.png
"""

import os
import struct
import zlib

SIZE = 16

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JAVA_OUT = os.path.join(REPO, "resourcepack", "java", "assets", "lemonpvp", "textures", "item")
BEDROCK_OUT = os.path.join(REPO, "resourcepack", "bedrock", "textures", "items")
BEDROCK_ICON = os.path.join(REPO, "resourcepack", "bedrock", "pack_icon.png")
JAVA_ICON = os.path.join(REPO, "resourcepack", "java", "pack.png")

# ---------------------------------------------------------------- Pixelbilder
# '.' ist immer transparent, alle anderen Zeichen kommen aus der Palette.

SWORD = """
..............ab
.............ab.
............ab..
...........ab...
..........ab....
.........ab.....
........ab......
.......ab.......
...g...ab.......
..ggg.ab........
...ggab.........
..hgb...........
.hh.............
hh..............
h...............
................
"""

DAGGER = """
................
............ab..
...........ab...
..........ab....
.........ab.....
........ab......
.......ab.......
..g...ab........
.ggg.ab.........
..ggab..........
..hg............
.hh.............
hh..............
h...............
................
................
"""

BOW = """
............aa..
..........aa..s.
.........a....s.
........a.....s.
.......a......s.
......a.......s.
.....a........s.
....a.........s.
....a.........s.
.....a........s.
......a.......s.
.......a......s.
........a.....s.
.........a....s.
..........aa..s.
............aa..
"""

STAFF = """
.........ooooo..
........ooOOOoo.
........oOOOOOo.
........ooOOOoo.
.........ooooo..
.......aa.......
......aa........
.....aa.........
....aa..........
...aa...........
..aa............
.haa............
hh..............
h...............
................
................
"""

SHIELD = """
..aaaaaaaaaaaa..
..absssssssssba.
..absssssssssba.
..abssseeesssba.
..abssseeesssba.
..absssssssssba.
..absssssssssba.
...abssssssssb..
...abssssssssb..
....abssssssb...
.....absssssb...
......abssb.....
.......abb......
........b.......
................
................
"""

HEART = """
................
...aaa....aaa...
..ahhha..ahhha..
.ahhhhhaahhhhha.
.ahhhhhhhhhhhha.
.ahhhhhhhhhhhha.
.ahhhhhhhhhhhha.
..ahhhhhhhhhha..
...ahhhhhhhha...
....ahhhhhha....
.....ahhhha.....
......ahha......
.......aa.......
................
................
................
"""

CRYSTAL = """
.......aa.......
......acca......
.....acccca.....
....acccccca....
...acccccccca...
..acccccccccca..
..acccccccccca..
..acccbbbbccca..
..acccccccccca..
...acccccccca...
....acccccca....
.....acccca.....
......acca......
.......aa.......
................
................
"""

LEMON = """
................
..........gg....
.........g......
....aaaaa.......
...allllla......
..alllllllla....
..allyyylllla...
.alllyyylllla...
.allllllllllla..
.allllllllllla..
..alllllllllla..
..aalllllllaa...
...aalllllaa....
.....aaaaa......
................
................
"""

RUNESTONE = """
................
....aaaaaaaa....
...asssssssa....
..assssrrssa....
..asssrrrrsa....
..assssrrssa....
..assssrrssa....
..assssrrssa....
..assssrrssa....
..assssrrssa....
..asssssssaa....
...aaaaaaaa.....
................
................
................
................
"""

TOKEN = """
................
.....aaaaaa.....
...aayyyyyyaa...
..ayyyyyyyyya...
..ayyyaaayyya...
.ayyyaayaayyya..
.ayyyaayaayyya..
.ayyyaayaayyya..
.ayyyaayaayyya..
.ayyyaayaayyya..
..ayyyaaayyya...
..ayyyyyyyyya...
...aayyyyyyaa...
.....aaaaaa.....
................
................
"""

# --------------------------------------------------------------- Item-Palette
# a = Kontur/Akzent, b = dunkle Kante, s = Flaeche, h = Griff/Fuellung,
# g = Parierstange bzw. Blatt, o/O = Kugel, e = Emblem, y = hell, c = Kristall,
# r = Rune

ITEMS = {
    "zitronenklinge": (SWORD, {
        "a": (0xF7, 0xF0, 0x5A), "b": (0x9E, 0xC7, 0x1B),
        "g": (0x5A, 0x4A, 0x1E), "h": (0x3A, 0x2E, 0x14),
    }),
    "sturmbogen": (BOW, {
        "a": (0x6F, 0xD9, 0xE8), "s": (0xE8, 0xF7, 0xFF),
    }),
    "schattendolch": (DAGGER, {
        "a": (0xB3, 0x7A, 0xE0), "b": (0x5B, 0x2C, 0x8A),
        "g": (0x2A, 0x1C, 0x3D), "h": (0x18, 0x10, 0x24),
    }),
    "feuerstab": (STAFF, {
        "a": (0x7A, 0x4A, 0x22), "h": (0x4A, 0x2C, 0x14),
        "o": (0xFF, 0x8A, 0x1E), "O": (0xFF, 0xE0, 0x6A),
    }),
    "heilerstab": (STAFF, {
        "a": (0x6B, 0x5A, 0x2E), "h": (0x45, 0x38, 0x1C),
        "o": (0x5A, 0xD8, 0x62), "O": (0xE6, 0xFF, 0xC2),
    }),
    "bollwerkschild": (SHIELD, {
        "a": (0xC9, 0xCF, 0xD6), "b": (0x6E, 0x76, 0x80),
        "s": (0x9A, 0xA3, 0xAD), "e": (0xF7, 0xF0, 0x5A),
    }),
    "heldenherz": (HEART, {
        "a": (0x7A, 0x10, 0x18), "h": (0xE8, 0x3A, 0x46),
    }),
    "lebenskristall": (CRYSTAL, {
        "a": (0x7B, 0x2C, 0x9E), "c": (0xE0, 0x8A, 0xF7),
        "b": (0xFF, 0xE8, 0xFF),
    }),
    "zitrone": (LEMON, {
        "a": (0xB8, 0x9A, 0x10), "l": (0xF7, 0xE0, 0x2A),
        "y": (0xFF, 0xF8, 0xB0), "g": (0x4C, 0xAF, 0x2E),
    }),
    "rueckkehrstein": (RUNESTONE, {
        "a": (0x1C, 0x3A, 0x42), "s": (0x2E, 0x6B, 0x75),
        "r": (0x7A, 0xF0, 0xE8),
    }),
    # Zusatztextur: das Waehrungssymbol fuer GUI und Werbung.
    "zitronen_token": (TOKEN, {
        "a": (0xB8, 0x9A, 0x10), "y": (0xF7, 0xE0, 0x2A),
    }),
}


def parse(art, palette):
    """ASCII-Art -> 16x16 RGBA-Pixelmatrix."""
    rows = [line for line in art.strip("\n").split("\n")]
    grid = []
    for y in range(SIZE):
        line = rows[y] if y < len(rows) else ""
        row = []
        for x in range(SIZE):
            char = line[x] if x < len(line) else "."
            if char == "." or char not in palette:
                row.append((0, 0, 0, 0))
            else:
                red, green, blue = palette[char]
                row.append((red, green, blue, 255))
        grid.append(row)
    return grid


def write_png(path, grid):
    height = len(grid)
    width = len(grid[0])

    raw = bytearray()
    for row in grid:
        raw.append(0)  # Filtertyp "None"
        for red, green, blue, alpha in row:
            raw += bytes((red, green, blue, alpha))

    def chunk(tag, data):
        body = tag + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)

    png = b"\x89PNG\r\n\x1a\n"
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(bytes(raw), 9))
    png += chunk(b"IEND", b"")

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as handle:
        handle.write(png)


def scale(grid, factor):
    scaled = []
    for row in grid:
        big_row = []
        for pixel in row:
            big_row.extend([pixel] * factor)
        for _ in range(factor):
            scaled.append(list(big_row))
    return scaled


def on_background(grid, background):
    """Legt ein Bild auf einen deckenden Hintergrund - fuer die Pack-Icons."""
    out = []
    for row in grid:
        new_row = []
        for red, green, blue, alpha in row:
            if alpha == 0:
                new_row.append(background + (255,))
            else:
                new_row.append((red, green, blue, 255))
        out.append(new_row)
    return out


def main():
    written = 0
    for item_id, (art, palette) in ITEMS.items():
        grid = parse(art, palette)
        write_png(os.path.join(JAVA_OUT, item_id + ".png"), grid)
        write_png(os.path.join(BEDROCK_OUT, item_id + ".png"), grid)
        written += 2

    icon = on_background(scale(parse(LEMON, ITEMS["zitrone"][1]), 8), (0x0C, 0x0C, 0x0C))
    write_png(BEDROCK_ICON, icon)
    write_png(JAVA_ICON, icon)
    written += 2

    print("PNG-Dateien geschrieben: %d" % written)


if __name__ == "__main__":
    main()
